# waveshare 3.49 hardware pack v1.07

# --- CLOCKS PACKAGE -----------------------------------------------------------
packages:
  clocks: !include ../clocks-wide.yaml

esphome:
  on_boot:
    - priority: 700
      then:
        - switch.turn_on: sys_en_hold

pca9554:
  - id: pca9554a_device
    address: 0x20
    i2c_id: bus_a

# --- BUSES / PERIPHERALS ------------------------------------------------------
i2c:
  - id: bus_a
    scl: GPIO48
    sda: GPIO47
    scan: true
  - id: bus_b
    scl: GPIO18
    sda: GPIO17
    scan: true
    frequency: 400kHz

# --- TOUCHSCREEN --------------------------------------------------------------
touchscreen:
  - platform: axs15231
    id: my_touchscreen
    i2c_id: bus_b
    address: 0x3b
    update_interval: 20ms
    display: main_display

    on_touch:
      then:
        - lambda: |-
            id(gs_touch_active) = true;

            // Mirror both axes like the vendor "Rotated" example (640x172)
            const int W = id(main_display).get_width();
            const int H = id(main_display).get_height();
            const int mx = W - touch.x;
            const int my = H - touch.y;

            id(gs_start_x) = mx;
            id(gs_start_y) = my;
            id(gs_last_x)  = mx;
            id(gs_last_y)  = my;
            id(gs_start_ms) = millis();

    on_update:
      then:
        - lambda: |-
            if (!id(gs_touch_active)) return;

            const int W = id(main_display).get_width();
            const int H = id(main_display).get_height();

            for (auto &t : touches) {
              if (t.state >= 1 && t.state <= 2) {
                const int mx = W - t.x;
                const int my = H - t.y;
                id(gs_last_x) = mx;
                id(gs_last_y) = my;
                break;
              }
            }

    on_release:
      then:
        - lambda: |-
            if (!id(gs_touch_active)) return;
            id(gs_touch_active) = false;

            // ---- per-gesture dedupe: run at most once per press ----
            static uint32_t last_handled_start_ms = 0;
            if (id(gs_start_ms) == last_handled_start_ms) {
              return;  // already handled this gesture
            }
            last_handled_start_ms = id(gs_start_ms);
            // --------------------------------------------------------

            // Deltas/time
            const int dx = id(gs_last_x) - id(gs_start_x);
            const int dy = id(gs_last_y) - id(gs_start_y);
            const uint32_t dt = millis() - id(gs_start_ms);

            // Screen-scaled thresholds
            const int w = id(main_display).get_width();
            const int h = id(main_display).get_height();
            const int min_dim = (w < h) ? w : h;

            const int MIN_DIST = std::max(16, min_dim / 8);
            const uint32_t MAX_TIME = 1500;

            // Tap thresholds
            const int TAP_MAX_DIST   = std::max(8,  min_dim / 20);
            const uint32_t TAP_MAX_TIME = 300;
            const uint32_t TAP_MIN_TIME = 120;

            const int absx = std::abs(dx);
            const int absy = std::abs(dy);

            // Require clear dominance to avoid diagonal jitter
            const float DOM = 1.30f;
            const bool swipe_h = (dt <= MAX_TIME) && (absx >= MIN_DIST) && (absx >= int(DOM * absy));
            const bool swipe_v = (dt <= MAX_TIME) && (absy >= MIN_DIST) && (absy >= int(DOM * absx));

            // Not a swipe → tap (require min press time)
            if (!(swipe_h || swipe_v)) {
              if (dt >= TAP_MIN_TIME &&
                  absx <= TAP_MAX_DIST && absy <= TAP_MAX_DIST &&
                  dt <= TAP_MAX_TIME) {
                id(pulse_touch_input).execute();
              }
              return;
            }

            // ---- Handle exactly ONE outcome ----
            if (swipe_h) {
              // LEFT if dx < 0, RIGHT if dx > 0
              // Do the style change directly here (single path).
              static const char* const opts[] = {
                "7-segment","Flip","Default","Presence","Weather","Small","Analog","Wide","Alarmstyle"
              };
              const int N = sizeof(opts)/sizeof(opts[0]);

              // current index
              std::string cur = id(clock_style).state.c_str();
              int idx = 0;
              for (int i = 0; i < N; i++) if (cur == opts[i]) { idx = i; break; }

              int next_idx = idx;
              if (dx < 0) {
                // LEFT → next
                next_idx = (idx + 1) % N;
              } else {
                // RIGHT → previous
                next_idx = (idx - 1 + N) % N;
              }

              // publish once; your select's on_value will refresh the page if needed
              id(clock_style).publish_state(opts[next_idx]);

              // no L/R pulses and no local L/R scripts (prevents double path)
              return;
            }

            // Vertical: keep your existing behavior (pulses + optional local)
            if (swipe_v) {
              if (dy < 0) {
                // UP
                id(pulse_swipe_up).execute();
                if (id(swipe_local).state) id(swipe_up_action).execute();
              } else {
                // DOWN
                id(pulse_swipe_down).execute();
                if (id(swipe_local).state) id(swipe_down_action).execute();
              }
            }

# --- BACKLIGHT ----------------------------------------------------------------
output:
  - platform: ledc
    id: backlight_output
    pin: GPIO8
    inverted: true

light:
  - platform: monochromatic
    id: Sled
    name: Screen
    icon: mdi:television
    entity_category: config
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

# --- AUDIO DEVICES ------------------------------------------------------------
switch:
  - platform: gpio
    id: sys_en_hold
    pin:
      pca9554: pca9554a_device
      number: 6
      mode: OUTPUT
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: Speaker Enable
    icon: "mdi:speaker"
    entity_category: config
    pin: GPIO42
    restore_mode: RESTORE_DEFAULT_ON

  - platform: gpio
    name: Speaker Switch
    icon: "mdi:speaker"
    entity_category: config
    pin:
      pca9554: pca9554a_device
      number: 7
    restore_mode: RESTORE_DEFAULT_ON

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO46
    i2s_bclk_pin: GPIO15
    i2s_mclk_pin: GPIO7

audio_adc:
  - platform: es7210
    i2c_id: bus_a
    id: es7210_adc
    bits_per_sample: 16bit
    sample_rate: 16000

audio_dac:
  - platform: es8311
    i2c_id: bus_a
    id: es8311_dac
    bits_per_sample: 16bit
    sample_rate: 48000

microphone:
  - platform: i2s_audio
    id: box_mic
    i2s_audio_id: i2s_audio_bus
    i2s_din_pin: GPIO6
    adc_type: external
    channel: left
    pdm: false
    sample_rate: 16000
    bits_per_sample: 16bit

speaker:
  - platform: i2s_audio
    id: box_speaker
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: GPIO45
    dac_type: external
    sample_rate: 48000
    channel: mono
    audio_dac: es8311_dac
    buffer_duration: 300ms

  - platform: mixer
    id: mixing_speaker
    output_speaker: box_speaker
    source_speakers:
      - id: announcement_mixing_input
      - id: media_mixing_input

  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    sample_rate: 48000

  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    sample_rate: 48000
    
media_player:
  - platform: speaker
    name: None
    id: external_media_player
    volume_increment: 0.05
    volume_min: 0.5
    volume_max: 0.8
    announcement_pipeline:
      speaker: announcement_resampling_speaker
      format: FLAC
      sample_rate: 16000
      num_channels: 1

    media_pipeline:
      speaker: media_resampling_speaker
      format: FLAC
      num_channels: 1
      sample_rate: 48000
    buffer_size: 250000

    on_announcement:
      - if:
          condition:
            - microphone.is_capturing:
          then:
            - script.execute: stop_wake_word
            - if:
                condition:
                  - lambda: return id(wake_word_engine_location).state == "In Home Assistant";
                then:
                  - wait_until:
                      condition:
                        - not:
                            voice_assistant.is_running:

      - if:
          condition:
            lambda: 'return id(playing_internal_sound);'
          then:
            - lambda: 'id(playing_internal_sound) = false;'
          else:
            - script.execute: reset_screensaver
            - display.page.show: now_playing_page
            - component.update: main_display

    on_play:
      - if:
          condition:
            - microphone.is_capturing:
          then:
            - script.execute: stop_wake_word
            - if:
                condition:
                  - lambda: return id(wake_word_engine_location).state == "In Home Assistant";
                then:
                  - wait_until:
                      condition:
                        - not:
                            voice_assistant.is_running:

      - if:
          condition:
            lambda: 'return id(playing_internal_sound);'
          then:
            - lambda: 'id(playing_internal_sound) = false;'
          else:
            - script.execute: reset_screensaver
            - display.page.show: now_playing_page
            - component.update: main_display

    on_idle:
      - if:
          condition:
            not:
              voice_assistant.is_running:
          then:
            - script.execute: start_wake_word
            - script.execute: set_idle_or_mute_phase
            - script.execute: draw_display

    files:
      - id: timer_finished_sound
        file: https://github.com/RealDeco/xiaozhi-esphome/raw/main/sounds/timer_finished.flac
      - id: wake_word_triggered_sound
        file: https://github.com/RealDeco/xiaozhi-esphome/raw/main/sounds/wake_word_triggered.flac
      - id: ready_sound
        file: ${startup_sound_file}


# --- BATTERY (FAKE SOURCE TO KEEP WIDGET HAPPY) -------------------------------
sensor:
  - platform: adc
    pin: GPIO4
    name: "Battery Voltage"
    id: battery_voltage
    attenuation: 12db
    accuracy_decimals: 2
    update_interval: 10s
    unit_of_measurement: "V"
    icon: mdi:battery-medium
    filters:
      - multiply: 3.0
      - median:
          window_size: 7
          send_every: 7
          send_first_at: 1
      - throttle: 1min
    on_value:
      then:
        - sensor.template.publish:
            id: battery_percentage
            state: !lambda 'return x;'

binary_sensor:
  - platform: gpio
    id: pwr_button
    name: "PWR Button"
    pin:
      number: GPIO16
      inverted: true
    on_multi_click:
      - timing:
          - ON for at least 1s
        then:
          - switch.turn_off: sys_en_hold
          - logger.log: "PWR long-press: power OFF"

# --- DISPLAY DRIVER -----------------------------------------------------------
#external_components:
#  - source: github://pr#11226
#    components: [display, mipi, mipi_spi]
#    refresh: 1h

spi:
  id: display_qspi
  type: quad
  clk_pin: 10
  data_pins: [11, 12, 13, 14]

display:
  - platform: mipi_spi
    id: main_display
    model: WAVESHARE-ESP32-S3-TOUCH-LCD-3.49
    rotation: ${rotate_display}
    pages: !include ../display_pages.yaml
