# simple yaml with sendspin mediaplayer for ESP32 WRover with 4MB PSRam.
esphome:
  name: esphome-web-96a060
  friendly_name: ClearCube
  min_version: 2025.11.0
  name_add_mac_suffix: false

esp32:
  variant: esp32
  framework:
    type: esp-idf

logger:
  level: debug

api:

ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: "RZ7D3EzJdPM6"

psram:
  mode: quad
  speed: 80MHz

http_request:
  
captive_portal:

external_components:
  - source: github://pr#12284
    components: [mdns, sendspin]
    refresh: 0s
  - source: github://pr#12253
    components: [ mixer ]
  - source: github://pr#12254
    components: [ resampler ]
  - source: github://pr#12256
    components: [ audio ]
  - source: github://pr#12258
    components: [ media_player ]
  - source: github://pr#10212
    components: [runtime_image, online_image]
    refresh: 0s
  - source: github://pr#12429
    components: [file, media_source, http_request, speaker_source]
    refresh: 0s

  - source:
      type: git
      url: https://github.com/kahrendt/esphome
      ref: wifi-power-save-wake-loop
    refresh: 0s
    components: [wifi]

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin:  GPIO33

speaker:
  - platform: i2s_audio
    id: box_speaker
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: GPIO32
    dac_type: external
    channel: stereo
    buffer_duration: 300ms

  - platform: mixer
    id: mixing_speaker
    output_speaker: box_speaker
    num_channels: 2
    source_speakers:
      - id: announcement_mixer_input
      - id: media_mixer_input

  - platform: resampler
    id: media_resampling_input
    output_speaker: media_mixer_input
    sample_rate: 48000

  - platform: resampler
    id: announcement_resampling_input
    output_speaker: announcement_mixer_input    
    sample_rate: 48000

sendspin:
  id: sendspin_hub
  task_stack_in_psram: true
  kalman_process_error: 0.01

media_source:
  - platform: sendspin
    id: sendspin_source
  - platform: http_request
    id: http_source
    buffer_size: 500000

media_player:
  - platform: sendspin
    id: sendspin_group_media_player
  - platform: speaker_source
    name: none
    id: external_media_player
    announcement_speaker: announcement_resampling_input
    media_speaker: media_resampling_input

    announcement_pipeline:
      format: FLAC
      num_channels: 1
      sample_rate: 48000
    media_pipeline:
      format: FLAC
      num_channels: 2      
      sample_rate: 48000

    volume_increment: 0.05
    volume_min: 0.5
    volume_max: 0.8
    sources:
      - http_source
      - sendspin_source
