substitutions:
    startup_sound_file: https://github.com/RealDeco/xiaozhi-esphome/raw/main/sounds/Home_Connected.flac

esphome:
  name: esphome-web-0096f0
  friendly_name: Muse Luxe
  min_version: 2026.1.0
  name_add_mac_suffix: false
  on_boot:
    priority: -100
    then:
      - script.execute: led_red

esp32:
  variant: esp32
  framework:
    type: esp-idf

logger:
  level: debug

api:
  on_client_connected:
    - lambda: |-
        if (!id(boot_sound_played)) {
          id(boot_sound_played) = true;
          if (id(startup_sound_switch).state) {
            id(play_sound)->execute(true, std::string("ready_sound"));
          }
        }
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: "RZ7D3EzJdPM6"

psram:
  mode: quad
  speed: 80MHz

http_request:
  
captive_portal:

external_components:
  - source:
      # https://github.com/esphome/esphome/pull/12253
      type: git
      url: https://github.com/esphome/esphome
      ref: 7f34908569650e5a8b8c83e6bf89fea561218880
    components: [mixer]
  - source:
      # https://github.com/esphome/esphome/pull/12254
      type: git
      url: https://github.com/esphome/esphome
      ref: 6006b896a691ad38d8045ac67564c168973d1a1d
    components: [resampler]
  - source:
      # https://github.com/esphome/esphome/pull/12256
      type: git
      url: https://github.com/esphome/esphome
      ref: 9148832ea4e54907bad71a24d4ced1ce6c862433
    components: [audio]
  - source:
      # https://github.com/esphome/esphome/pull/12258
      type: git
      url: https://github.com/esphome/esphome
      ref: bff22983a390352360796f8e1363127e0cd1f898
    components: [media_player]
  - source:
      # https://github.com/esphome/esphome/pull/12284
      type: git
      url: https://github.com/esphome/esphome
      ref: a6c0a861a014e64c67d46115eba8e5370777b80a
    components: [mdns, sendspin]
  - source:
      # https://github.com/esphome/esphome/pull/12429
      type: git
      url: https://github.com/esphome/esphome
      ref: 928204066ce0082404573ea1c6a0b58aeebbd7c6
    refresh: 0s
    components: [file, http_request, media_source, speaker_source]
  - source:
      type: git
      url: https://github.com/kahrendt/esphome
      ref: wifi-power-save-wake-loop
    refresh: 0s
    components: [wifi]
  - source: github://pr#3552
    components: [es8388]
    refresh: 0s


i2c:
  sda: GPIO18
  scl: GPIO23
  frequency: 100kHz
  id: bus_a

es8388:

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin:  GPIO5

speaker:
  - platform: i2s_audio
    id: box_speaker
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: GPIO26
    dac_type: external
    channel: stereo
    buffer_duration: 300ms

  - platform: mixer
    id: mixing_speaker
    output_speaker: box_speaker
    num_channels: 2
    source_speakers:
      - id: announcement_mixer_input
      - id: media_mixer_input

  - platform: resampler
    id: media_resampling_input
    output_speaker: media_mixer_input
    sample_rate: 48000

  - platform: resampler
    id: announcement_resampling_input
    output_speaker: announcement_mixer_input    
    sample_rate: 48000

sendspin:
  id: sendspin_hub
  task_stack_in_psram: true
  kalman_process_error: 0.01

media_source:
  - platform: sendspin
    id: sendspin_source
  - platform: http_request
    id: http_source
    buffer_size: 500000
  - platform: file
    id: file_source
    files:
      - id: ready_sound
        file: ${startup_sound_file}

media_player:
  - platform: sendspin
    id: sendspin_media_player
  - platform: speaker_source
    name: none
    id: external_media_player
    announcement_speaker: announcement_resampling_input
    media_speaker: media_resampling_input

    announcement_pipeline:
      format: FLAC
      num_channels: 1
      sample_rate: 48000
    media_pipeline:
      format: FLAC
      num_channels: 2      
      sample_rate: 48000

    volume_increment: 0.05
    volume_min: 0.5
    volume_max: 0.9
    sources:
      - http_source
      - sendspin_source
      - file_source
    on_state:
      then:
        - lambda: |-
            using media_player::MediaPlayerState;

            auto state = id(external_media_player).state;

            if (
              state == MediaPlayerState::MEDIA_PLAYER_STATE_PLAYING ||
              state == MediaPlayerState::MEDIA_PLAYER_STATE_ANNOUNCING
            ) {
              id(led_green).execute();
            } else {
              id(led_red).execute();
            }


script:
  - id: play_sound
    parameters:
      priority: bool
      sound_file: string
    then:
      - if:
          condition:
            lambda: return priority;
          then:
            - media_player.stop:
                id: external_media_player
                announcement: true
      - lambda: |-
          if ( (id(external_media_player).state != media_player::MediaPlayerState::MEDIA_PLAYER_STATE_ANNOUNCING ) || priority) {
            id(external_media_player)
              ->make_call()
              .set_media_url("file://" + sound_file)
              .set_announcement(true)
              .perform();
          }
  - id: led_red
    then:
      - light.turn_on:
          id: led
          red: 100%
          green: 0%
          blue: 0%
          brightness: 100%

  - id: led_green
    then:
      - light.turn_on:
          id: led
          red: 0%
          green: 100%
          blue: 0%
          brightness: 100%

switch:
  - platform: template
    id: startup_sound_switch
    name: Startup sound
    icon: "mdi:card-text-outline"
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON

globals:
  - id: boot_sound_played
    type: bool
    restore_value: no
    initial_value: "false"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
      inverted: true
      mode:
        input: true
        output: false
        open_drain: false
        pullup: true
        pulldown: false
      drive_strength: 20.0
    name: Button
    on_press:
      then:
        - media_player.toggle: sendspin_media_player

  - platform: gpio
    pin:
      number: GPIO19
      inverted: true
      mode:
        input: true
        pullup: true
    name: Volume Up
    on_click:
      - media_player.volume_up:
          id: external_media_player

  - platform: gpio
    pin:
      number: GPIO32
      inverted: true
      mode:
        input: true
        pullup: true
    name: Volume Down
    on_click:
      - media_player.volume_down:
          id: external_media_player

light:
  - platform: esp32_rmt_led_strip
    id: led
    name: LED light
    disabled_by_default: false
    entity_category: config
    pin: GPIO22
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 1
    rgb_order: grb
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%

sensor:
 - platform: adc
   pin: GPIO33
   name: Battery
   icon: "mdi:battery-outline"
   update_interval: 15s
   accuracy_decimals: 3
   attenuation: 11db
   raw: true
   filters:
    - multiply: 0.00173913 # 2300 -> 4, for attenuation 11db, based on Olivier's code
    - exponential_moving_average:
        alpha: 0.2
        send_every: 2
    - delta: 0.002
